config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies
  resources :lists do
    resources :bookmarks
  end
end

#                    movies GET    /movies(.:format)                                                                        movies#index
#                           POST   /movies(.:format)                                                                        movies#create
#                 new_movie GET    /movies/new(.:format)                                                                    movies#new
#                edit_movie GET    /movies/:id/edit(.:format)                                                               movies#edit
#                     movie GET    /movies/:id(.:format)                                                                    movies#show
#                           PATCH  /movies/:id(.:format)                                                                    movies#update
#                           PUT    /movies/:id(.:format)                                                                    movies#update
#                           DELETE /movies/:id(.:format)                                                                    movies#destroy
#            list_bookmarks GET    /lists/:list_id/bookmarks(.:format)                                                      bookmarks#index
#                           POST   /lists/:list_id/bookmarks(.:format)                                                      bookmarks#create
#         new_list_bookmark GET    /lists/:list_id/bookmarks/new(.:format)                                                  bookmarks#new
#        edit_list_bookmark GET    /lists/:list_id/bookmarks/:id/edit(.:format)                                             bookmarks#edit
#             list_bookmark GET    /lists/:list_id/bookmarks/:id(.:format)                                                  bookmarks#show
#                           PATCH  /lists/:list_id/bookmarks/:id(.:format)                                                  bookmarks#update
#                           PUT    /lists/:list_id/bookmarks/:id(.:format)                                                  bookmarks#update
#                           DELETE /lists/:list_id/bookmarks/:id(.:format)                                                  bookmarks#destroy
#                     lists GET    /lists(.:format)                                                                         lists#index
#                           POST   /lists(.:format)                                                                         lists#create
#                  new_list GET    /lists/new(.:format)                                                                     lists#new
#                 edit_list GET    /lists/:id/edit(.:format)                                                                lists#edit
#                      list GET    /lists/:id(.:format)                                                                     lists#show
#                           PATCH  /lists/:id(.:format)                                                                     lists#update
#                           PUT    /lists/:id(.:format)                                                                     lists#update
#                           DELETE /lists/:id(.:format)                                                                     lists#destroy
#        rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :chef]

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def edit
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movie, notice: 'movie was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /movies/1
  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'movie was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /movies/1
  def destroy
    @movie.destroy
    redirect_to movies, notice: 'movie was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_movie
    @movie = Movie.find(params[:id])
  end

    # Only allow a trusted parameter "white list" through.
  def movie_params
    params.require(:movie).permit(:name, :poster_url, :overview)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1500&q=80);">
  <div class="container">
    <h1>What's your <em>mood</em> ?</h1>
    <p>Search the perfect list for your mood</p>

  </div>
</div>

<div class="container d-flex text-center" id="home">
   <% @lists.each do |l| %>
        <div class="card mx-auto mt-3" style="width: 18rem;">
        <img class="card-img-top" src="<%= l.category_url %>" alt="Card image cap">
          <div class="card-body">
            <div class="card-title">
              <h5><strong><%= l.name%> </strong></h5>
            </div>
              <%= link_to "Discover the list", list_path(l), class: "btn btn-light"%>
          </div>
        </div>
  <%end%>
</div>

<div class="container d-flex" id="home">
        <div class="card mx-auto mt-3 text-center" style="width: 18rem;">
        <img class="card-img-top" src="https://images.unsplash.com/photo-1496262967815-132206202600?ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8cXVlc3Rpb258ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60" alt="Card image cap">
          <div class="card-body">
            <div class="card-title">
              <h5><strong>Create your list</strong></h5>
            </div>
              <%= link_to "CREATE", new_list_path, class: "btn btn-dark"%>
          </div>
        </div>

</div>

app/views/movies/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1504&q=80);">
  <div class="container">
    <h1>Better than Netflix</h1>
    <p>Find the best selection of movies to watch</p>

  </div>
</div>

<div class="container d-flex" id="home">
   <% @movies.each do |m| %>
        <div class="card mx-auto" style="width: 18rem;">
        <img class="card-img-top" src="<%= m.poster_url %>" alt="Card image cap">
          <div class="card-body">
            <div class="card-title">
              <h5><strong><%= m.title %> </strong></h5>
            </div>
            <div class="card-text">
              <p><%= m.overview %></p>
              <%= link_to "See details", movie_path(m), class: "btn btn-light"%>
            </div>
          </div>
        </div>
  <%end%>
</div>

app/views/movies/show.html.erb
<div class="card mx-auto py-10 text-center" style="width: 30rem;">
  <img class="card-img-top" src="<%= @movie.poster_url %>" alt="Card image cap">
  <div class="card-body mx-auto">
    <div class="card-title">
      <h3><%= @movie.title %> </h3>
    </div>
    <div class="card-text">
      <p><%= @movie.overview%></p>
    </div>
  </div>
  <%= link_to 'leave Review', movies_path(@movie), class: "btn btn-dark" %>
</div>